# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: ci+cd

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
permissions: write-all

jobs:
  ci:

    runs-on: ubuntu-latest

    steps:
    - name: Check-out repository
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install poetry
      uses: snok/install-poetry@v1
    - name: Install packages
      run: poetry install
    - name: Build documentation
      run: poetry run make html --directory docs/

  cd:
    needs: ci

    # Only run this job if new work is pushed to "main"
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    runs-on: ubuntu-latest

    steps:
    - name: Check-out repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install poetry
      uses: snok/install-poetry@v1
    - name: Install packages
      run: poetry install

    - name: Use Python Semantic Release to prepare release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        poetry run semantic-release publish

